version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            database:
                condition: service_started
            # rabbitmq:
            #     condition: service_healthy
        networks:
            - safartick

    # rabbitmq:
    #     image: registry.cn-hangzhou.aliyuncs.com/google_containers/rabbitmq:3.10-management
    #     ports:
    #         - '5672:5672'
    #         - '15672:15672'
    #     healthcheck:
    #         test: ['CMD', 'rabbitmqctl', 'status']
    #         interval: 10s
    #         retries: 5
    #         start_period: 10s
    #         timeout: 5s
    #     networks:
    #         - safartick

    # database:
    #     image: postgres:14
    #     restart: always
    #     environment:
    #         POSTGRES_PASSWORD: safartick@hd6730mrm
    #     volumes:
    #         - ./docker/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    #     ports:
    #         - '5433:5432'
    #     networks:
    #         - safartick

    database:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: safartick@hd6730mrm
        volumes:
            - ./docker/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
        ports:
            - '3307:3306'
        networks:
            - safartick

networks:
    safartick:
        external: true
        driver: bridge
